version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: medusa-server
    ports:
      - "9000:9000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
    image: storefront
    container_name: medusa-storefront
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: http://backend:9000

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: caddy-medusa
    depends_on:
      - storefront
      - backend
    ports:
      - "80:80"
      - "443:443"