services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backend-uploads:/app/backend/uploads
    environment:
      REDIS_URL: redis://cache
      NODE_ENV: development
      PORT: 9000

  postgres:
    image: postgres:10.4
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cache

  storefront:
    build:
      context: ./storefront
      dockerfile: Dockerfile
      args:
        - MEDUSA_BACKEND_URL=https://api.studiosammii.com
    image: storefront
    container_name: medusa-storefront
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_MEDUSA_BACKEND_URL: https://api.studiosammii.com
      NEXT_PUBLIC_MEDUSA_BACKEND_DOMAIN: api.studiosammii.com

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: caddy-medusa
    depends_on:
      - storefront
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy-data:/data