services:
  backend:
    build:
      context: ./studio-sammii-v2
      dockerfile: Dockerfile
    image: backend
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    env_file:
      - ./studio-sammii-v2/.env
    volumes:
      - ./backend-uploads:/app/backend/uploads
    environment:
      REDIS_URL: redis://cache
      NODE_ENV: production
      PORT: 9000
    ports:
      - 9000:9000

  postgres:
    image: postgres:10.4
    env_file:
      - ./studio-sammii-v2/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cache

  storefront:
    build:
      context: ./studio-sammii-v2-storefront
      dockerfile: Dockerfile
      args:
        - MEDUSA_BACKEND_URL=https://api.studiosammii.com
    image: storefront
    container_name: medusa-storefront
    depends_on:
      - backend
    env_file:
      - ./studio-sammii-v2-storefront/.env
    ports:
      - 8000:8000